### ISSUE TITLE
Firebase Cloud Messaging (FCM) Compatible? 

### ISSUE THREAD

**Issue by MattMorgis** [discourse/discourse-push-notifications#6]
More of a question than an issue.

When visiting https://developers.google.com/cloud-messaging/, the following message is displayed: 

> Firebase Cloud Messaging (FCM) is the new version of GCM. It inherits the reliable and scalable GCM infrastructure, plus new features! See the FAQ to learn more. If you are integrating messaging in a new app, start with FCM. GCM users are strongly recommended to upgrade to FCM, in order to benefit from new FCM features today and in the future.

Is it safe to get an API key from FCM or should I register this plugin with GCM? If anything is needed to get it working with FCM I'd be willing to lend a hand.

**Comment by ssaavedra** [comment]
According to the Firebase pages, Firebase Cloud Messaging as such is only available for Android and iOS native apps, so Push API serviceWorkers should rely on the GCM API.
